#!/bin/bash
# Sekha v1.x to v2.0 Configuration Migration Script
# This script helps migrate from v1.x environment variables to v2.0 config.yaml

set -e

COLOR_RESET="\033[0m"
COLOR_BOLD="\033[1m"
COLOR_GREEN="\033[32m"
COLOR_YELLOW="\033[33m"
COLOR_RED="\033[31m"
COLOR_BLUE="\033[34m"

echo -e "${COLOR_BOLD}${COLOR_BLUE}"
echo "╔═══════════════════════════════════════════════════════╗"
echo "║   Sekha v1.x → v2.0 Configuration Migration Tool     ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo -e "${COLOR_RESET}"

# Check if .env exists
if [ ! -f ".env" ]; then
    echo -e "${COLOR_YELLOW}⚠️  No .env file found. Will use example config.${COLOR_RESET}"
    ENV_EXISTS=false
else
    echo -e "${COLOR_GREEN}✓ Found .env file${COLOR_RESET}"
    ENV_EXISTS=true
fi

# Source .env if it exists
if [ "$ENV_EXISTS" = true ]; then
    export $(cat .env | grep -v '^#' | xargs)
fi

# Backup existing config if present
if [ -f "config.yaml" ]; then
    BACKUP_FILE="config.yaml.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${COLOR_YELLOW}⚠️  Backing up existing config.yaml to ${BACKUP_FILE}${COLOR_RESET}"
    cp config.yaml "$BACKUP_FILE"
fi

echo ""
echo -e "${COLOR_BOLD}Detecting current configuration...${COLOR_RESET}"

# Detect LLM provider
LLM_PROVIDER=${LLM_PROVIDER:-"ollama"}
LLM_URL=${LLM_URL:-"http://localhost:11434"}
LLM_MODEL=${LLM_MODEL:-"llama3.1:8b"}
EMBEDDING_MODEL=${EMBEDDING_MODEL:-"nomic-embed-text"}

echo "  Current LLM Provider: $LLM_PROVIDER"
echo "  Current LLM URL: $LLM_URL"
echo "  Current Chat Model: $LLM_MODEL"
echo "  Current Embedding Model: $EMBEDDING_MODEL"

# Detect API keys
OPENAI_API_KEY=${OPENAI_API_KEY:-""}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-""}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-""}

echo ""
echo -e "${COLOR_BOLD}Generating v2.0 configuration...${COLOR_RESET}"

# Generate config.yaml based on detected settings
cat > config.yaml << EOF
# Sekha v2.0 Configuration
# Generated by migration script on $(date)
# Original v1.x settings migrated from .env

config_version: "2.0"

llm_providers:
EOF

# Add primary provider based on v1.x settings
if [ "$LLM_PROVIDER" = "ollama" ]; then
    cat >> config.yaml << EOF
  # Primary provider: Ollama (from v1.x LLM_PROVIDER)
  - id: "ollama_primary"
    type: "ollama"
    base_url: "${LLM_URL}"
    api_key: null
    priority: 1
    models:
      - model_id: "${EMBEDDING_MODEL}"
        task: "embedding"
        context_window: 512
        dimension: 768
      - model_id: "${LLM_MODEL}"
        task: "chat_small"
        context_window: 8192
      - model_id: "${LLM_MODEL}"
        task: "chat_smart"
        context_window: 8192
EOF
fi

# Add OpenAI if key present
if [ -n "$OPENAI_API_KEY" ]; then
    echo -e "${COLOR_GREEN}✓ Detected OpenAI API key, adding as fallback provider${COLOR_RESET}"
    cat >> config.yaml << EOF

  # OpenAI fallback (detected from OPENAI_API_KEY)
  - id: "openai_fallback"
    type: "openai"
    base_url: "https://api.openai.com/v1"
    api_key: "\${OPENAI_API_KEY}"
    priority: 2
    models:
      - model_id: "gpt-4o-mini"
        task: "chat_small"
        context_window: 128000
      - model_id: "gpt-4o"
        task: "chat_smart"
        context_window: 128000
        supports_vision: true
      - model_id: "text-embedding-3-large"
        task: "embedding"
        context_window: 8191
        dimension: 3072
EOF
fi

# Add Anthropic if key present
if [ -n "$ANTHROPIC_API_KEY" ]; then
    echo -e "${COLOR_GREEN}✓ Detected Anthropic API key, adding as provider${COLOR_RESET}"
    PRIORITY=3
    [ -z "$OPENAI_API_KEY" ] && PRIORITY=2
    cat >> config.yaml << EOF

  # Anthropic (detected from ANTHROPIC_API_KEY)
  - id: "anthropic"
    type: "anthropic"
    base_url: "https://api.anthropic.com/v1"
    api_key: "\${ANTHROPIC_API_KEY}"
    priority: ${PRIORITY}
    models:
      - model_id: "claude-3-sonnet-20240229"
        task: "chat_small"
        context_window: 200000
      - model_id: "claude-3-opus-20240229"
        task: "chat_smart"
        context_window: 200000
EOF
fi

# Add OpenRouter if key present
if [ -n "$OPENROUTER_API_KEY" ]; then
    echo -e "${COLOR_GREEN}✓ Detected OpenRouter API key, adding as provider${COLOR_RESET}"
    PRIORITY=4
    [ -z "$OPENAI_API_KEY" ] && [ -z "$ANTHROPIC_API_KEY" ] && PRIORITY=2
    cat >> config.yaml << EOF

  # OpenRouter (detected from OPENROUTER_API_KEY)
  - id: "openrouter"
    type: "openrouter"
    base_url: "https://openrouter.ai/api/v1"
    api_key: "\${OPENROUTER_API_KEY}"
    priority: ${PRIORITY}
    models:
      - model_id: "deepseek/deepseek-v3"
        task: "chat_smart"
        context_window: 64000
      - model_id: "moonshot/kimi-2.5"
        task: "chat_smart"
        context_window: 256000
        supports_vision: true
EOF
fi

# Add default models section
cat >> config.yaml << EOF

default_models:
  embedding: "${EMBEDDING_MODEL}"
  chat_fast: "${LLM_MODEL}"
  chat_smart: "${LLM_MODEL}"
EOF

if [ -n "$OPENAI_API_KEY" ]; then
    cat >> config.yaml << EOF
  chat_vision: "gpt-4o"
EOF
fi

# Add routing configuration
cat >> config.yaml << EOF

routing:
  auto_fallback: true
  require_vision_for_images: true
  max_cost_per_request: null  # Set to limit costs (e.g., 0.50 for \$0.50)
  circuit_breaker:
    failure_threshold: 3
    timeout_secs: 60
    success_threshold: 2
EOF

echo -e "${COLOR_GREEN}✓ Generated config.yaml${COLOR_RESET}"

# Create updated .env.v2 file
echo ""
echo -e "${COLOR_BOLD}Generating updated environment variables...${COLOR_RESET}"

cat > .env.v2 << EOF
# Sekha v2.0 Environment Variables
# Generated by migration script on $(date)

# ============================================
# BREAKING CHANGES FROM v1.x:
# - LLM_URL → LLM_BRIDGE_URL
# - LLM_PROVIDER removed (configured in config.yaml)
# - LLM_MODEL → PREFERRED_CHAT_MODEL (optional hint)
# ============================================

# Controller
CONTROLLER_URL=http://sekha-controller:8080
CONTROLLER_API_KEY=${CONTROLLER_API_KEY:-test_key_12345678901234567890123456789012}

# Bridge (v2.0: proxy talks to bridge, not direct LLM)
LLM_BRIDGE_URL=http://sekha-llm-bridge:5001
LLM_TIMEOUT=120

# Optional: Preferred models (bridge uses as hints)
PREFERRED_CHAT_MODEL=${LLM_MODEL}
PREFERRED_EMBEDDING_MODEL=${EMBEDDING_MODEL}

# Proxy
PROXY_HOST=0.0.0.0
PROXY_PORT=8081

# Memory
AUTO_INJECT_CONTEXT=true
CONTEXT_TOKEN_BUDGET=2000
CONTEXT_LIMIT=5
DEFAULT_FOLDER=/auto-captured

# API Keys (load from config.yaml via \${VAR} syntax)
EOF

if [ -n "$OPENAI_API_KEY" ]; then
    echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> .env.v2
fi

if [ -n "$ANTHROPIC_API_KEY" ]; then
    echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> .env.v2
fi

if [ -n "$OPENROUTER_API_KEY" ]; then
    echo "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}" >> .env.v2
fi

echo -e "${COLOR_GREEN}✓ Generated .env.v2${COLOR_RESET}"

# Summary
echo ""
echo -e "${COLOR_BOLD}${COLOR_GREEN}╔═══════════════════════════════════════════════════════╗${COLOR_RESET}"
echo -e "${COLOR_BOLD}${COLOR_GREEN}║          Migration Complete! Next Steps:              ║${COLOR_RESET}"
echo -e "${COLOR_BOLD}${COLOR_GREEN}╚═══════════════════════════════════════════════════════╝${COLOR_RESET}"
echo ""
echo "1. Review generated files:"
echo "   - config.yaml (provider configuration)"
echo "   - .env.v2 (updated environment variables)"
echo ""
echo "2. Replace old .env with new one:"
echo -e "   ${COLOR_BLUE}cp .env.v2 .env${COLOR_RESET}"
echo ""
echo "3. Test the configuration:"
echo -e "   ${COLOR_BLUE}docker-compose -f docker/docker-compose.yml config${COLOR_RESET}"
echo ""
echo "4. Restart the stack:"
echo -e "   ${COLOR_BLUE}docker-compose down && docker-compose up -d${COLOR_RESET}"
echo ""
echo "5. Verify routing is working:"
echo -e "   ${COLOR_BLUE}curl http://localhost:5001/api/v1/models${COLOR_RESET}"
echo ""
echo -e "${COLOR_YELLOW}📚 For more details, see:${COLOR_RESET}"
echo "   - docs/migration-guide-v2.md"
echo "   - docs/configuration-v2.md"
echo "   - config.yaml.example"
echo ""

if [ "$ENV_EXISTS" = false ]; then
    echo -e "${COLOR_YELLOW}⚠️  Note: No .env file was found. Generated config may need adjustment.${COLOR_RESET}"
    echo -e "${COLOR_YELLOW}   Review config.yaml and add your API keys to .env.v2${COLOR_RESET}"
fi

echo -e "${COLOR_GREEN}✨ Happy routing! Your Sekha stack is now v2.0-ready.${COLOR_RESET}"
echo ""
